language: generic

jobs:
  include:
    # Minimal job for PowerPC with Ubuntu Jammy
    - os: linux
      name: PPC64
      arch: ppc64le
      dist: jammy
    # Minimal job for System Z with Ubuntu Jammy
    - os: linux
      name: S390X
      arch: s390x
      dist: jammy
    # Minimal job for ARM64 with Ubuntu Jammy
    - os: linux
      name: ARM64
      arch: arm64
      dist: jammy

script:
  - echo "Running test script..."
  - uname -a
