language: generic

# Specify the architecture
arch:
  - ppc64le

dist: focal

install:
  - echo "No dependencies to install"

script:
  - echo "Testing on ppc64le architecture"
  - uname -m
  - echo "Running generic tests"
